version: "3"

services:

  runtime-setup:
    image: swift-nio-ssh:20.04-5.6
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.6"

  test:
    image: swift-nio-ssh:20.04-5.6
    environment: []
      - MAX_ALLOCS_ALLOWED_client_server_many_small_commands_per_connection=267850
      - MAX_ALLOCS_ALLOWED_client_server_one_command_per_connection=1100050
      - MAX_ALLOCS_ALLOWED_client_server_streaming_large_message_in_small_chunks=65100
      #- SANITIZER_ARG=--sanitize=thread
      #- WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors

  shell:
    image: swift-nio-ssh:20.04-5.6
